apiVersion: v1
kind: Service
metadata:
 name: wordpress
 labels:
   app: wordpress
   namespace: jingy-wp-activity
spec:
 ports:
   - port: 80
     protocol: TCP
     targetPort: 80
 selector:
   app: wordpress
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
 labels:
   app: wordpress
spec:
 selector:
   matchLabels:
     app: wordpress
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: wordpress
   spec:
     containers:
     - image: wordpress:6.2.1-apache
       name: wordpress
       ports:
       - containerPort: 80
         name: wordpress
       env:
       - name: WORDPRESS_DB_HOST
         value: mysql
       - name: WORDPRESS_DB_USER
         value: dbuser
       - name: WORDPRESS_DB_PASSWORD
         value: dbpassword